server:
  port: 8080

spring:
  application:
    name: java-app
  
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    
  cache:
    type: redis
    redis:
      time-to-live: 10000ms # 10 segundos

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.devops.challenge: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"